export type ContentSection = { title: string; body: string; bullets?: string[] };
export type EditorialSection = {
  title: string;
  body: string;
  bullets?: string[];
  steps?: string[];
  links?: { label: string; href: string }[];
};
export type SeoPage = {
  slug: string; title: string; h1: string; description: string; intro: string;
  group: string; overview: string; requirements: string[]; sequence: string[];
  controls: ContentSection[]; productCategories: string[]; serviceLinks: { label: string; service: string }[];
  technologies: { label: string; href: string }[]; related: string[]; faqs: { question: string; answer: string }[];
  editorialSections?: EditorialSection[];
};

const services = {
  plc: { label: "PLC programming", service: "PLC Programming" },
  hmi: { label: "HMI programming", service: "HMI Programming" },
  vfd: { label: "VFD programming", service: "VFD and Servo Programming" },
  panel: { label: "Control panel design and manufacturing", service: "Control Panel Design and Manufacturing" },
  machine: { label: "Machine automation", service: "Machine Automation" },
  retrofit: { label: "Automation retrofit", service: "Automation Retrofit and Machine Modification" },
  scada: { label: "SCADA development", service: "SCADA Development" },
} as const;
const tech = {
  plc: { label: "PLC systems", href: "/plc" }, hmi: { label: "HMI operator interfaces", href: "/hmi" },
  vfd: { label: "Variable frequency drives", href: "/vfd" }, servo: { label: "Servo and motion control", href: "/servo-automation" },
  process: { label: "Process automation", href: "/process-automation" }, weight: { label: "Weighing automation", href: "/weighing-automation" },
  panel: { label: "Control panels", href: "/control-panels" },
} as const;
type AppSeed = { slug: string; name: string; title?: string; seoDescription?: string; intro?: string; group: string; overview: string; requirements: string[]; sequence: string[]; controls: ContentSection[]; products?: string[]; services?: (keyof typeof services)[]; related?: string[]; faqs?: { question: string; answer: string }[]; editorialSections?: EditorialSection[] };
const sequence = (items: string[]) => items;
const commonControls = (plc = true): ContentSection[] => [
  ...(plc ? [{ title: "PLC sequence and interlocks", body: "The PLC sequence is defined from the machine states, operator actions, permissives and fault responses agreed for the project. Manual and automatic modes should have clear transitions and reset behavior." }] : []),
  { title: "Operator interface", body: "An HMI can present operating status, alarms, setpoints and permitted commands in a way that reflects the process. The required screens and access levels depend on the machine and operating procedure." },
];
function makeApp(seed: AppSeed): SeoPage {
  const name = seed.name;
  const controls = seed.controls;
  return {
    slug: seed.slug, title: seed.title ?? name, h1: name,
    description: seed.seoDescription ?? `${seed.overview} Discuss PLC, operator interface, drives, instrumentation and interlocks for your ${name.toLowerCase()} requirements with SmartPLC Solutions.`,
    intro: seed.intro ?? `${seed.overview} Automation scope depends on the equipment, operating sequence, existing controls and process requirements. Share the machine details and desired outcome to define a suitable control approach.`,
    group: seed.group, overview: seed.overview, requirements: seed.requirements, sequence: seed.sequence,
    controls, productCategories: seed.products ?? ["plc", "hmi"],
    serviceLinks: (seed.services ?? ["plc", "hmi", "machine"]).map((k) => services[k]),
    technologies: Array.from(new Map((seed.products ?? ["plc", "hmi"]).map((key) => {
      const map: Record<string, { label: string; href: string }> = { plc: tech.plc, hmi: tech.hmi, "vfd-drives": tech.vfd, "servo-systems": tech.servo, "control-panels": tech.panel, sensors: tech.process };
      return [map[key]?.href, map[key]] as const;
    }).filter(([href]) => Boolean(href))).values()),
    related: seed.related ?? [],
    editorialSections: seed.editorialSections,
    faqs: seed.faqs ?? [
      { question: `What information is useful for a ${name.toLowerCase()} enquiry?`, answer: "Describe the machine or process, current controls, operating sequence, required modes, available drawings and the changes you want to make. Include known controller and drive models where possible." },
      { question: "Can existing equipment be considered?", answer: "Yes. Include the installed controller, HMI, drives, sensors and any drawings or fault details so the existing arrangement can be reviewed before defining scope." },
    ],
  };
}

const automationControls = (kind: "conveyor" | "mixing" | "batch" | "printing" | "pump" | "machine"): ContentSection[] => {
  const first: Record<typeof kind, ContentSection> = {
    conveyor: { title: "Conveyor sequence, sensors and interlocks", body: "Define each conveyor's start permissives, downstream-ready condition, material detection, stop sequence and fault response. Multi-conveyor operation can be sequenced so upstream equipment responds to downstream availability." },
    mixing: { title: "Batch, weigh and mix sequence", body: "A project may coordinate material selection, measured addition, mixing time and discharge steps. Load-cell use, weighing accuracy, recipe storage and correction logic must be agreed against the actual weighing equipment and process." },
    batch: { title: "Batching and material flow", body: "The sequence can be organized around material selection, measured dosing, transfer, mixing and discharge. The required weighing devices, tolerance handling and batch records depend on the plant design." },
    printing: { title: "Printing sequence and web handling", body: "Control scope can include station coordination, line speed references, registration inputs and coordinated acceleration or deceleration. Tension and cut control depend on the machine mechanics and installed feedback devices." },
    pump: { title: "Pump duty and pressure control", body: "A control sequence can select lead or standby equipment, monitor pressure feedback and apply run permissives and alarms. PID and VFD control are suitable only where the pump, drive and hydraulic arrangement support them." },
    machine: { title: "Machine states and operating sequence", body: "Document the machine cycle, operator actions, required permissives, abnormal conditions and safe recovery path before mapping them to controller logic." },
  };
  return [
    { title: "PLC sequence and machine states", body: "Translate the agreed process into explicit states, transitions, permissives, alarms and recovery behavior. The final sequence should be reviewed against the machine's actual operating procedure." },
    first[kind],
    { title: "Operator interface and alarms", body: "An HMI may show mode, step, status, setpoints and actionable alarm information. Screen behavior and operator permissions should match the plant's procedures." },
    ...(kind === "conveyor" || kind === "mixing" || kind === "batch" || kind === "printing" || kind === "pump" ? [{ title: "Motor drives and instrumentation", body: "Where installed equipment supports it, drives can be controlled through suitable hardwired or network interfaces. Sensors and transmitters should be selected and scaled to the machine and process requirements." }] : []),
    { title: "Safety and fault handling", body: "Safety functions must be designed for the risk assessment and applicable machine requirements. Standard PLC logic should not be treated as a substitute for safety-rated hardware or a validated safety design." },
  ];
};

const applicationSeeds: AppSeed[] = [
  { slug:"conveyor-automation", name:"Conveyor Automation & PLC Control", group:"Manufacturing & Machine Automation", overview:"PLC-based conveyor automation coordinates material movement, conveyor zones and connected equipment across a production or handling process.", requirements:["Conveyor layout, direction and zone boundaries","Start/stop sequence and downstream-ready behavior","Photoelectric, proximity or other installed detection points","Drive control, speed requirements and fault response"], sequence:sequence(["Confirm downstream equipment is ready and permissives are met","Start conveyors in the agreed downstream-to-upstream order","Monitor zone sensors, drive status and material movement","Stop or inhibit upstream zones when downstream equipment is unavailable","Annunciate faults and define reset and restart conditions"]), controls:automationControls("conveyor"), products:["plc","hmi","vfd-drives","sensors","industrial-communication"], services:["plc","hmi","vfd","panel","machine"], related:["production-line-automation","cut-to-length-automation","packaging-machine-automation"], faqs:[{question:"Can a PLC coordinate multiple conveyors?",answer:"A PLC can coordinate multiple conveyor zones when the required signals, controller capacity, drive interfaces and operating sequence are defined. The layout and restart behavior should be reviewed for the specific line."},{question:"Can conveyor speed be controlled with a VFD?",answer:"Where a suitable motor and drive are installed, the control design can include speed references and drive status. Required speed range and mechanics need to be confirmed."}] },
  { slug:"sand-mixing-plant-automation", name:"Sand Mixing Plant Automation & PLC Control", group:"Manufacturing & Machine Automation", overview:"Sand mixing automation can coordinate material selection, weighing, addition, mixing and discharge as a defined plant sequence.", requirements:["Plant layout, material sources and discharge destinations","Batch recipe parameters and operator permissions","Load cells or other weighing equipment and required tolerances","Mixer, conveyor and feeder motor details","Manual, automatic, cleaning and fault-recovery procedures"], sequence:["Select an approved recipe and verify plant permissives","Weigh and add materials in the defined order","Confirm measured quantities and handle out-of-range conditions","Run the mixing step for configured process conditions","Discharge the batch and return equipment to the next permitted state"], controls:automationControls("mixing"), products:["plc","hmi","vfd-drives","sensors","industrial-communication"], services:["plc","hmi","vfd","panel","machine"], related:["batching-plant-automation","production-line-automation","soap-production-line-automation"], faqs:[{question:"Can the system include weighing and load cells?",answer:"Load-cell integration can be considered when the weighing hardware, signal interface, mechanical installation and required accuracy are known. No accuracy or compatibility should be assumed before reviewing those details."},{question:"Can recipes be managed through an HMI?",answer:"Recipe entry and selection can be included when requirements for permitted values, user access, storage and change control are defined for the plant."}] },
  { slug:"batching-plant-automation", name:"Batching Plant Automation & PLC Control", group:"Manufacturing & Machine Automation", overview:"Batching plant control organizes material dosing, weighing, transfer and mixing into repeatable sequences based on the plant's process requirements.", requirements:["Material bins, feeders, gates and transfer routes","Batch quantities, tolerances and sequence order","Weighing hardware and signal interfaces","Mixer and conveying equipment states","Alarm, manual operation and batch handling rules"], sequence:["Check plant readiness, selected materials and destination","Dose materials against configured batch targets","Verify each measurement and apply defined tolerance handling","Transfer materials and execute the mixing step","Discharge and prepare the plant for the next batch"], controls:automationControls("batch"), products:["plc","hmi","vfd-drives","sensors","industrial-communication"], services:["plc","hmi","vfd","panel","machine"], related:["sand-mixing-plant-automation","production-line-automation","soap-production-line-automation"] },
  { slug:"die-casting-automation", name:"Die Casting Machine Automation", group:"Manufacturing & Machine Automation", overview:"Die casting automation coordinates machine-cycle signals, operator controls and auxiliary equipment around the installed casting machine.", requirements:["Machine sequence and existing controller interface","Clamp, injection and ejection cycle signals","Auxiliary equipment and part-handling interfaces","Operator modes, alarms and recovery procedure"], sequence:["Verify machine and auxiliary permissives","Initiate the permitted cycle step","Monitor available cycle-complete and fault signals","Coordinate auxiliary handling where included in scope","Require the defined operator action before recovery or restart"], controls:automationControls("machine"), products:["plc","hmi","sensors","industrial-communication"], related:["core-shooter-automation","production-line-automation"] },
  { slug:"core-shooter-automation", name:"Core Shooter Machine Automation", group:"Manufacturing & Machine Automation", overview:"Core shooter control can sequence machine states and linked auxiliaries around the equipment's documented operating procedure.", requirements:["Installed machine and controller details","Cycle steps, permissives and operator controls","Core box or auxiliary device signals available to automation","Fault, reset and manual operating procedures"], sequence:["Confirm setup and machine-ready conditions","Execute the configured cycle stages in sequence","Monitor stage feedback and configured timeouts","Signal cycle completion and required operator actions","Handle faults through documented reset conditions"], controls:automationControls("machine"), products:["plc","hmi","sensors","control-panels"], related:["die-casting-automation","machine-automation"] },
  { slug:"cutting-machine-automation", name:"Cutting Machine Automation", group:"Manufacturing & Machine Automation", overview:"Cutting machine automation can coordinate feed, cut-cycle signals and material handling according to the machine's mechanics and required sequence.", requirements:["Material feed and cutting mechanism details","Length, count or position inputs required by the process","Drive and actuator interfaces","Guard, interlock and restart requirements"], sequence:["Load or confirm material and required job settings","Position or feed material to the defined cut point","Enable the cut cycle when permissives are satisfied","Confirm cycle completion and advance or unload material","Track faults and require the agreed reset procedure"], controls:automationControls("machine"), products:["plc","hmi","vfd-drives","servo-systems","sensors"], related:["cut-to-length-automation","production-line-automation"] },
  { slug:"drilling-machine-automation", name:"Drilling Machine Automation", group:"Manufacturing & Machine Automation", overview:"Drilling machine control can coordinate feed, spindle, workholding and cycle feedback according to the machine configuration.", requirements:["Spindle and feed mechanisms","Workpiece detection and clamping signals","Required cycle modes and operator controls","Existing drive, sensor and safety interfaces"], sequence:["Confirm workpiece and clamping permissives","Run spindle and feed according to the configured cycle","Monitor end-of-travel or process feedback","Retract and signal cycle completion","Handle abnormal conditions through defined recovery steps"], controls:automationControls("machine"), products:["plc","hmi","vfd-drives","sensors"], related:["tapping-machine-automation","machine-automation"] },
  { slug:"tapping-machine-automation", name:"Tapping Machine Automation", group:"Manufacturing & Machine Automation", overview:"Tapping machine automation can coordinate spindle direction, feed and cycle transitions where the machine hardware provides suitable control interfaces.", requirements:["Spindle and reversal method","Feed mechanism and cycle limits","Workpiece sensing and clamping conditions","Operator setup and fault recovery requirements"], sequence:["Verify workpiece and machine permissives","Advance through the configured tapping cycle","Control reversal or return according to the machine design","Confirm cycle completion and readiness for the next part","Raise faults for missing feedback or abnormal cycle conditions"], controls:automationControls("machine"), products:["plc","hmi","vfd-drives","servo-systems","sensors"], related:["drilling-machine-automation","machine-automation"] },
  { slug:"printing-machine-automation", name:"Printing Machine Automation", group:"Printing & Converting", overview:"Printing machine automation coordinates line operation, operator settings and available web-handling or station signals.", requirements:["Machine stations and installed control architecture","Line speed references and available feedback","Registration, web path and tension requirements","Start, stop, splice and fault procedures"], sequence:["Confirm web path and station readiness","Start and coordinate stations using the agreed sequence","Apply line speed and relevant process references","Monitor feedback, alarms and operator adjustments","Stop or recover the line according to documented procedure"], controls:automationControls("printing"), products:["plc","hmi","vfd-drives","servo-systems","sensors","industrial-communication"], services:["plc","hmi","vfd","panel","machine"], related:["rotogravure-printing-automation","pharmaceutical-foil-printing-automation","unwinding-automation","winding-automation"] },
  { slug:"rotogravure-printing-automation", name:"Rotogravure Printing Automation", group:"Printing & Converting", overview:"Rotogravure printing automation can coordinate printing stations, web movement and relevant line references based on the installed machine and its feedback devices.", requirements:["Station arrangement and existing drive system","Web speed and tension control requirements","Registration or synchronization signals","Unwind, rewind and operator procedures"], sequence:["Verify web path, station setup and drive readiness","Establish the configured line reference","Coordinate station operation and available registration feedback","Monitor tension, drive status and configured alarms","Manage deceleration, stop and restart under defined conditions"], controls:automationControls("printing"), products:["plc","hmi","vfd-drives","servo-systems","sensors","industrial-communication"], related:["printing-machine-automation","unwinding-automation","winding-automation","cut-to-length-automation"] },
  { slug:"pharmaceutical-foil-printing-automation", name:"Pharmaceutical Foil Printing Automation", group:"Printing & Converting", overview:"Foil printing automation can coordinate the installed print line, material movement and operator-controlled process settings.", requirements:["Machine stations and existing automation equipment","Material path, speed references and feedback","Registration and tension requirements where applicable","Documented operating and changeover sequence"], sequence:["Confirm material path and machine setup","Bring stations to their configured ready state","Run coordinated line operation using available references","Monitor process feedback and machine alarms","Follow agreed changeover, stop and restart procedures"], controls:automationControls("printing"), products:["plc","hmi","vfd-drives","servo-systems","sensors"], related:["printing-machine-automation","rotogravure-printing-automation","unwinding-automation"] },
  { slug:"membrane-press-automation", name:"Membrane Press Automation", group:"Manufacturing & Machine Automation", overview:"Membrane press automation sequences machine states, operator selections and available temperature or pressure feedback around the press design.", requirements:["Press cycle and actuator arrangement","Temperature or pressure inputs required by the process","Workpiece and guard interlocks","Recipe, dwell and operator mode requirements"], sequence:["Verify setup, guards and process permissives","Apply the configured cycle conditions","Advance through press, dwell and release stages","Monitor available process feedback and alarms","Return the machine to a defined safe operating state"], controls:[...automationControls("machine"),{title:"Temperature and pressure feedback",body:"If the process uses measured temperature or pressure, identify the sensor type, operating range, control method and required response before defining the loop."}], products:["plc","hmi","sensors","control-panels"], related:["temperature-control","pressure-control","machine-automation"] },
  { slug:"heat-treatment-furnace-automation", name:"Heat Treatment Furnace Automation", group:"Process Automation", overview:"Furnace automation can coordinate heating stages, temperature measurement and process sequence according to the furnace and treatment requirements.", requirements:["Furnace zones, heating equipment and installed controller","Sensor types, placement and required temperature ranges","Heating, soak and cooling stages","Alarm limits, operator access and batch documentation needs"], sequence:["Check furnace readiness and selected process settings","Run configured heating stages using available feedback","Monitor measured process values and alarms","Advance through soak or subsequent stages by defined conditions","Complete the cycle and record or signal its status as required"], controls:[...commonControls(),{title:"Temperature loop and process stages",body:"Temperature control strategy depends on furnace zones, sensor placement, thermal response and required process tolerances. Setpoints, ramp behavior and alarm limits must come from the approved process specification."}], products:["plc","hmi","sensors","industrial-communication"], related:["temperature-control","pid-control","process-automation"] },
  { slug:"packaging-machine-automation", name:"Packaging Machine Automation", group:"Manufacturing & Machine Automation", overview:"Packaging machine automation coordinates product feed, packaging stages and discharge using signals and cycle requirements from the installed equipment.", requirements:["Packaging format and machine cycle","Product detection and feed equipment","Required speed, count and reject signals","Operator changeover and fault recovery steps"], sequence:["Verify packaging material and machine readiness","Feed or register product for the configured cycle","Coordinate packaging and sealing stages where installed","Count output and monitor configured fault signals","Stop, clear and restart through defined operator steps"], controls:automationControls("machine"), products:["plc","hmi","vfd-drives","servo-systems","sensors"], related:["production-line-automation","soap-production-line-automation","conveyor-automation"] },
  { slug:"baling-machine-automation", name:"Baling Machine Automation", group:"Manufacturing & Machine Automation", overview:"Baling machine control can coordinate feed, compression and bale handling stages around the installed press and hydraulic system.", requirements:["Feed and compression cycle details","Hydraulic and position feedback available","Bale tie or discharge interfaces if installed","Operator access, interlocks and recovery steps"], sequence:["Confirm machine and feed permissives","Feed material to the configured condition","Run the compression stage using available feedback","Signal tie or discharge steps where included","Return to ready state after the defined reset checks"], controls:automationControls("machine"), products:["plc","hmi","sensors","control-panels"], related:["machine-automation","production-line-automation"] },
  { slug:"production-line-automation", name:"Production Line Automation", group:"Manufacturing & Machine Automation", overview:"Production line automation coordinates connected machines, material transfer, line states and operator information across a defined manufacturing flow.", requirements:["Process layout and equipment boundaries","Machine-ready, cycle-complete and fault signals","Line modes, buffers and material flow rules","Operator stations, alarms and restart behavior"], sequence:["Establish line readiness from connected equipment","Start equipment in the agreed order","Coordinate material flow and buffer conditions","Respond to downstream stops and equipment faults","Resume only when required permissives are restored"], controls:automationControls("conveyor"), products:["plc","hmi","vfd-drives","sensors","industrial-communication"], related:["conveyor-automation","packaging-machine-automation","soap-production-line-automation"] },
  { slug:"soap-production-line-automation", name:"Soap Production Line Automation", group:"Manufacturing & Machine Automation", overview:"Soap production line controls can coordinate process stages, material transfer and packaging equipment according to the actual plant layout.", requirements:["Production stages and equipment sequence","Batch or continuous process inputs","Temperature, level or weighing feedback where required","Transfer, packaging and cleaning procedures"], sequence:["Confirm material and equipment readiness","Run the configured preparation or processing steps","Coordinate transfer between defined stages","Monitor available process values and equipment status","Signal completion and required cleaning or changeover actions"], controls:automationControls("batch"), products:["plc","hmi","vfd-drives","sensors","industrial-communication"], related:["batching-plant-automation","production-line-automation","temperature-control"] },
  { slug:"pump-automation", name:"Pump Automation & PLC Control", group:"Utilities", overview:"Pump automation can manage pump starts, operating status and pressure or level conditions around the hydraulic system and installed equipment.", requirements:["Pump duty, motor and starter or drive details","Pressure, level or flow measurements required","Lead/standby and changeover rules","Dry-run, fault and restart handling requirements"], sequence:["Check demand and pump permissives","Start the selected pump and confirm available run feedback","Adjust operation against the defined process signal if supported","Switch or stop according to configured demand and fault rules","Alarm abnormal conditions and apply defined reset behavior"], controls:automationControls("pump"), products:["plc","hmi","vfd-drives","sensors","industrial-communication"], services:["plc","hmi","vfd","panel","machine"], related:["booster-pump-automation","pressure-control","level-control","flow-control"], faqs:[{question:"Can a pump PLC use pressure feedback for automatic control?",answer:"Pressure-based control can be considered when a suitable transmitter, pump arrangement and control device are available. The required setpoint behavior, operating range and protection conditions must be defined."},{question:"Is a VFD required for pump automation?",answer:"No. Pump control may use different starting and control arrangements. Drive use depends on the pump, motor, hydraulic requirements and desired operating behavior."}] },
  { slug:"compressor-automation", name:"Compressor Automation", group:"Utilities", overview:"Compressor automation can coordinate run requests, available pressure feedback and equipment status according to the compressor and air-system design.", requirements:["Compressor type and installed controller interface","Pressure measurement and required operating band","Lead/standby or sequencing needs","Permissives, alarms and restart conditions"], sequence:["Check system demand and compressor readiness","Issue a permitted run request or sequence command","Monitor available pressure and equipment status","Coordinate standby equipment if defined in the system scope","Handle faults and restart only under documented conditions"], controls:[...automationControls("pump"),{title:"Pressure band and equipment protection",body:"Pressure targets, unloading behavior, start limits and minimum off times must respect compressor manufacturer requirements and the system design."}], products:["plc","hmi","sensors","industrial-communication"], related:["pump-automation","booster-pump-automation","pressure-control"] },
  { slug:"booster-pump-automation", name:"Booster Pump Automation", group:"Utilities", overview:"Booster pump control can maintain a defined system pressure by coordinating available pumps and pressure feedback where the installed arrangement supports it.", requirements:["Pump count, duty arrangement and motor details","Pressure sensor range and location","Demand behavior and pump changeover rules","Protection, alarm and restart requirements"], sequence:["Verify demand and available pump permissives","Start the required pump or pumps according to the configured strategy","Monitor system pressure and pump feedback","Change operating state as demand changes within defined limits","Stop or alarm on configured faults and protection conditions"], controls:automationControls("pump"), products:["plc","hmi","vfd-drives","sensors"], related:["pump-automation","pressure-control","pid-control"] },
  { slug:"ahu-automation", name:"AHU Automation", group:"Utilities", overview:"AHU automation coordinates fans and available air-side measurements and equipment signals based on the building or process requirements.", requirements:["Fan and damper arrangement","Temperature, pressure or air-quality measurements required","Operating schedule and occupied modes","Filter, freeze and equipment alarm inputs where installed"], sequence:["Check schedule, demand and equipment permissives","Enable the configured fans and associated devices","Monitor required measurements and equipment feedback","Apply agreed setpoint or mode changes","Stop and alarm according to the equipment sequence"], controls:[...automationControls("machine"),{title:"Air-side process signals",body:"Sensor types, locations, control ranges and sequence depend on the AHU design and the ventilation requirements supplied for the project."}], products:["plc","hmi","vfd-drives","sensors","industrial-communication"], related:["hvac-automation","temperature-control","pressure-control"] },
  { slug:"hvac-automation", name:"HVAC Automation", group:"Utilities", overview:"HVAC automation coordinates relevant heating, cooling, ventilation and equipment states around the installed system and operating requirements.", requirements:["System equipment and control boundaries","Temperature and other required sensor locations","Operating schedules, modes and setpoints","Equipment permissives, alarms and overrides"], sequence:["Evaluate schedule, demand and system readiness","Enable relevant equipment in the configured order","Monitor process feedback and equipment status","Adjust control outputs within approved operating limits","Report alarms and return equipment to the required state"], controls:[...automationControls("machine"),{title:"Temperature and system control",body:"Temperature loops and equipment sequencing depend on sensor placement, system response and the HVAC design. Operating values should be supplied by the responsible project engineer."}], products:["plc","hmi","vfd-drives","sensors","industrial-communication"], related:["ahu-automation","temperature-control","pid-control"] },
  { slug:"pvd-coating-automation", name:"PVD Coating Process Automation", group:"Process Automation", overview:"PVD process controls can organize machine states, cycle steps and available vacuum or process signals according to the coating equipment design.", requirements:["Coating system and existing controller details","Documented cycle stages and permissives","Vacuum and process signals available from installed instruments","Recipe, alarm and batch handling needs"], sequence:["Check chamber, utilities and system readiness","Run the configured preparation and cycle stages","Monitor available vacuum and process feedback","Complete the cycle and signal the required release state","Record or report faults for controlled recovery"], controls:[...automationControls("machine"),{title:"Vacuum and process instrumentation",body:"Control interfaces and limits must follow the installed vacuum equipment, sensor ranges and validated process requirements. No specific coating result or process capability is assumed."}], products:["plc","hmi","sensors","industrial-communication"], related:["process-automation","pid-control","machine-automation"] },
  { slug:"cut-to-length-automation", name:"Cut-to-Length Automation", group:"Printing & Converting", overview:"Cut-to-length systems coordinate material feed, length measurement and cutting based on machine mechanics and installed motion equipment.", requirements:["Material type and feed mechanism","Length measurement source and required repeatability","Cutting cycle and blade or actuator interface","Speed, synchronization and operator job settings"], sequence:["Load job length and quantity parameters","Feed material while monitoring length feedback","Synchronize or stop feed at the configured cut point","Execute cut and confirm cycle completion","Index material and report count or fault state"], controls:[...automationControls("printing"),{title:"Length and motion control",body:"Length measurement and axis control require suitable feedback and mechanics. Servo or encoder-based control should be selected only after reviewing the actual machine and accuracy needs."}], products:["plc","hmi","vfd-drives","servo-systems","sensors"], related:["cutting-machine-automation","printing-machine-automation","winding-automation","unwinding-automation"] },
  { slug:"unwinding-automation", name:"Unwinding Automation", group:"Printing & Converting", overview:"Unwinding controls coordinate roll supply and web movement with downstream equipment using the feedback available on the line.", requirements:["Unwind stand and brake or drive arrangement","Roll diameter or web feedback if available","Required tension behavior and line speed reference","Splice, stop and roll-change procedures"], sequence:["Prepare roll and confirm web path","Establish line-ready and unwind permissives","Coordinate unwind output with downstream line demand","Monitor available tension, speed or drive feedback","Support defined splice, stop and roll-change states"], controls:[...automationControls("printing"),{title:"Web tension and roll behavior",body:"Tension control may use different feedback and actuator arrangements. The roll mechanics, material limits and installed sensors determine whether closed-loop control is appropriate."}], products:["plc","hmi","vfd-drives","servo-systems","sensors"], related:["winding-automation","rotogravure-printing-automation","cut-to-length-automation"] },
  { slug:"winding-automation", name:"Winding Automation", group:"Printing & Converting", overview:"Winding automation coordinates web take-up, line speed and roll handling around the winding mechanism and available feedback.", requirements:["Winder arrangement and drive details","Required roll diameter or tension feedback","Speed reference and synchronization needs","Core, splice, stop and roll-change procedures"], sequence:["Confirm core, material path and machine permissives","Synchronize winding with the incoming line reference","Adjust operation as roll conditions change where supported","Monitor drive and process feedback","Complete stop and roll-change steps in the agreed sequence"], controls:[...automationControls("printing"),{title:"Winding tension and speed",body:"Tension and taper behavior require machine-specific parameters and suitable feedback. The control method should be defined with the web material, roll geometry and drive arrangement."}], products:["plc","hmi","vfd-drives","servo-systems","sensors"], related:["unwinding-automation","rotogravure-printing-automation","cut-to-length-automation"] },
];

export const applications = applicationSeeds.map(makeApp);
export const applicationGroups = ["Manufacturing & Machine Automation", "Printing & Converting", "Process Automation", "Utilities"];
export const applicationBySlug = new Map(applications.map((page) => [page.slug, page]));

const capabilitySeeds: AppSeed[] = [
  {slug:"industrial-automation",name:"Industrial Automation",group:"Automation Engineering",overview:"Industrial automation connects control systems, machines, instrumentation and operator workflows to support defined manufacturing and process requirements.",requirements:["Process goals, equipment boundaries and operating requirements","Existing PLC, HMI, drive and instrumentation details","Interfaces to upstream or downstream systems","Commissioning, support and documentation needs"],sequence:["Review the process and existing equipment","Agree control scope, interfaces and operating modes","Implement and review the required control behavior","Verify operation against the agreed sequence","Document handover and unresolved dependencies"],controls:automationControls("machine"),products:["plc","hmi","vfd-drives","servo-systems","sensors","control-panels","industrial-communication"],services:["plc","hmi","vfd","panel","machine","retrofit","scada"],related:["process-automation","machine-automation","applications"]},
  {
    slug: "plc",
    name: "PLC Systems for Industrial Automation",
    title: "PLC for Industrial Automation | PLC Systems",
    seoDescription: "PLC systems for industrial automation, machine and process control. Explore PLC products, programming services, and HMI, VFD, sensor and communication integration.",
    intro: "Explore programmable logic controllers (PLCs) for industrial machine control, production lines and process automation. This guide explains PLC operation, system integration and selection considerations, alongside real PLC products and links to programming services.",
    group: "Technology",
    overview: "A PLC automation project begins with the machine or process functions, field signals, operating modes and equipment interfaces that need to be controlled. The controller, I/O and connected devices are selected to suit that defined scope.",
    requirements: [
      "Machine or process functions, operating sequence and operator modes",
      "Digital and analog signals, field devices and actuator interfaces",
      "HMI, VFD, servo, SCADA and communication needs where applicable",
      "Installation environment, diagnostics, expansion and future I/O needs",
    ],
    sequence: [
      "Read the available input states from sensors and connected devices",
      "Evaluate the programmed logic, sequence conditions and interlocks",
      "Update output commands to connected equipment according to the logic",
      "Exchange status and operator commands with compatible HMI or supervisory systems",
    ],
    controls: [
      { title: "PLC sequence, modes and interlocks", body: "Control logic can organize machine states, manual and automatic operation, timers, counters, alarms and fault responses. The required behavior comes from the machine sequence and its operating requirements.", bullets: ["Define permissives and interlocks for each sequence step", "Handle startup, shutdown, abnormal conditions and reset behavior", "Provide clear status and alarm information for operators"] },
      { title: "PLC integration with HMI, drives and field devices", body: "A PLC can exchange commands and status with compatible HMI panels, VFDs, servo systems, sensors and other equipment. The available interfaces and control functions depend on the selected devices and machine design." },
    ],
    products: ["plc", "industrial-communication"],
    services: ["plc", "hmi", "machine", "retrofit", "panel"],
    related: ["plc-programming", "machine-automation", "process-automation", "automation-retrofit", "control-panels"],
    editorialSections: [
      {
        title: "What Is a PLC in Industrial Automation?",
        body: "A programmable logic controller (PLC) is an industrial controller that reads signals from field devices, evaluates a stored control program, and updates outputs connected to machinery or process equipment. It provides a way to coordinate machine automation, manufacturing operations and process control using logic tied to the physical system.",
        bullets: ["Digital inputs report discrete states such as a sensor, pushbutton or limit switch.", "Digital outputs command discrete devices such as an indicator, relay or contactor interface.", "Analog inputs measure variable signals such as temperature, pressure, flow or level when suitable instruments and I/O are provided.", "Analog outputs can provide a variable reference to compatible equipment where the control design requires one."],
      },
      {
        title: "How PLCs Are Used in Industrial Automation",
        body: "A PLC program combines input conditions, sequence logic, interlocks, timers and counters to decide when equipment may operate and what should happen next. In machine automation, it can coordinate cycles, conveyors, motors and packaging equipment. In process automation, it can use suitable instruments and outputs as part of temperature, pressure, flow or level control. Batching and weighing sequences can coordinate measured additions and material transfer when compatible weighing equipment is provided. These functions depend on the actual signals, controller, actuators and process requirements.",
        links: [
          { label: "Industrial automation", href: "/industrial-automation" },
          { label: "Machine automation", href: "/machine-automation" },
          { label: "Process automation", href: "/process-automation" },
          { label: "PLC-based conveyor automation", href: "/applications/conveyor-automation" },
          { label: "PLC batching and weighing automation", href: "/applications/batching-plant-automation" },
          { label: "PLC-based pump automation", href: "/applications/pump-automation" },
          { label: "Temperature control", href: "/temperature-control" },
          { label: "Pressure control", href: "/pressure-control" },
          { label: "Weighing automation", href: "/weighing-automation" },
        ],
      },
      {
        title: "PLC-Based Industrial Automation Architecture",
        body: "A typical control arrangement connects field devices to PLC inputs, uses programmed logic to coordinate the process, and sends output commands to drives or other actuators. An HMI provides an operator view and may send permitted commands or setpoints back to the PLC. SCADA may provide supervisory monitoring where the site architecture requires it. The exact signal path and hardware depend on the machine or process.",
        steps: ["Sensors and field devices → PLC inputs or compatible communication interface", "PLC → control logic, sequence states, alarms and interlocks", "PLC ↔ HMI or SCADA → operator status, commands and process values", "PLC → VFD, servo, contactor interface, valve or other actuator → machine or process"],
        bullets: ["Digital and analog I/O are selected for the actual sensors and actuators.", "Temperature, pressure, flow and level measurements require suitable instruments and signal interfaces.", "Load cells and encoders are used when the application and compatible interface require them.", "Safety functions require an appropriate safety design; standard PLC logic alone is not a substitute for safety-rated equipment or validation."],
      },
      {
        title: "PLC Programming for Industrial Automation",
        body: "PLC programming translates an agreed machine or process sequence into controller logic. Depending on the platform and project, this may use ladder logic, timers, counters, state transitions, sensor conditions, actuator commands, manual and automatic modes, alarms, and fault handling. Startup and shutdown behavior, commissioning checks and troubleshooting should be considered with the installed equipment and operating procedure.",
        links: [{ label: "PLC programming services", href: "/plc-programming" }],
      },
      {
        title: "How to Select a PLC for an Industrial Machine",
        body: "Choose a PLC from the machine requirements and compatible equipment rather than from a brand name alone. The selection should leave suitable capacity for the defined application and any documented expansion needs.",
        bullets: ["Count digital inputs and outputs and identify their signal types.", "Identify analog inputs and outputs, ranges and required signal conditioning.", "Check for high-speed inputs or pulse outputs only when the process requires them.", "Confirm required interfaces such as RS485, Modbus or Ethernet against the connected devices.", "Review HMI, VFD, servo and SCADA compatibility and communication needs.", "Account for I/O expansion, diagnostics, installation environment and control complexity."],
      },
      {
        title: "PLC Communication and Integration",
        body: "A PLC may exchange data with an HMI, VFD, servo drive, sensor interface or SCADA system through supported hardwired signals or communication protocols. Modbus over RS485 or Ethernet and industrial Ethernet are options only when the specific devices support the required protocol, topology and data mapping. Confirm the interface and behavior for communication loss during design.",
        links: [
          { label: "HMI operator interfaces", href: "/hmi" },
          { label: "VFD and motor control", href: "/vfd" },
          { label: "Servo automation", href: "/servo-automation" },
          { label: "SCADA programming and integration", href: "/scada-programming" },
          { label: "Industrial communication products", href: "/products/category/industrial-communication" },
        ],
      },
      {
        title: "PLC Applications in Industry",
        body: "PLC control is used across different kinds of industrial equipment, but not every PLC or configuration is suitable for every machine. I/O capacity, processing, communication, motion functions and environmental requirements should be matched to the application.",
        links: [
          { label: "Conveyor automation", href: "/applications/conveyor-automation" },
          { label: "Batching plant automation", href: "/applications/batching-plant-automation" },
          { label: "Sand mixing plant automation", href: "/applications/sand-mixing-plant-automation" },
          { label: "Printing machine automation", href: "/applications/printing-machine-automation" },
          { label: "Cutting machine automation", href: "/applications/cutting-machine-automation" },
          { label: "Drilling machine automation", href: "/applications/drilling-machine-automation" },
          { label: "Tapping machine automation", href: "/applications/tapping-machine-automation" },
          { label: "Heat treatment furnace automation", href: "/applications/heat-treatment-furnace-automation" },
          { label: "Pump automation", href: "/applications/pump-automation" },
          { label: "Compressor automation", href: "/applications/compressor-automation" },
          { label: "Production line automation", href: "/applications/production-line-automation" },
          { label: "Packaging machine automation", href: "/applications/packaging-machine-automation" },
        ],
      },
      {
        title: "PLC vs Relay Control",
        body: "Relay control can suit a simple, fixed circuit. A PLC may be useful when requirements include a changing sequence, multiple operating modes, timers or counters, alarms, operator interface, communication, diagnostics or program changes. The appropriate control method depends on the machine functions, interfaces, maintenance needs and project constraints; a PLC is not automatically the right choice for every system.",
      },
    ],
    faqs: [
      { question: "What is a PLC used for in industrial automation?", answer: "A PLC reads input signals, evaluates programmed conditions and controls connected outputs to coordinate an industrial machine or process. Typical functions include sequence control, interlocks, alarms and communication with operator or drive equipment where supported." },
      { question: "How does a PLC control an industrial machine?", answer: "The controller reads its inputs, executes the control program and updates outputs. The program defines sequence steps, permissives, modes and fault responses for the connected equipment." },
      { question: "What is PLC-based automation?", answer: "PLC-based automation uses a programmable controller with suitable I/O and interfaces to coordinate machine or process functions. The configuration depends on the required signals, sequence and connected devices." },
      { question: "Which PLC is suitable for an industrial machine?", answer: "That depends on the machine's digital and analog I/O, control complexity, communication, motion requirements, environment and expansion needs. Confirm the connected-device compatibility before selecting a controller." },
      { question: "Can a PLC control a VFD?", answer: "A PLC can command and monitor a VFD when the controller and drive have compatible hardwired or network interfaces and the control design is configured for them." },
      { question: "Can a PLC communicate with an HMI?", answer: "Yes, when the PLC and HMI support a compatible communication interface and their data mapping is configured. The HMI can then display status and provide permitted operator commands." },
      { question: "Can PLC automation be used for process control?", answer: "A PLC can support process control when suitable instruments, I/O and control outputs are provided. Loop behavior and operating limits must be defined for the actual process." },
      { question: "Can an existing machine be upgraded with PLC automation?", answer: "A retrofit may be possible after reviewing the existing controller, wiring, drawings, machine behavior and interfaces. See the automation retrofit capability for scope considerations." },
      { question: "What information is needed to select a PLC?", answer: "Provide the machine sequence, I/O list or available drawings, connected sensors and actuators, communication needs, HMI and drive models, installation environment and any expansion requirements." },
      { question: "Can SmartPLC provide PLC programming services?", answer: "PLC programming is an existing SmartPLC service. Share the controller details, machine sequence, drawings and required changes through the PLC programming service enquiry." },
      { question: "Where can I buy industrial PLCs?", answer: "Browse the real PLC products currently listed in the SmartPLC catalog. Product details and availability should be confirmed for the exact model and application." },
    ],
  },
  {slug:"plc-programming",name:"PLC Programming Services",group:"Engineering Services",overview:"PLC programming defines machine or process behavior in controller logic based on agreed operating requirements and installed hardware.",requirements:["Machine sequence and state descriptions","Electrical drawings and I/O details","Controller model, software and access arrangements","Alarm, recovery and handover expectations"],sequence:["Review the equipment and control narrative","Map I/O, states, permissives and abnormal conditions","Implement logic for the agreed controller","Review and verify behavior against the sequence","Document scope, assumptions and changes"],controls:commonControls(),products:["plc","industrial-communication"],services:["plc","machine","retrofit"],related:["plc","hmi-programming","control-panels"]},
  {slug:"process-automation",name:"Process Automation",group:"Process Automation",overview:"Process automation monitors and controls industrial variables such as temperature, pressure, flow, level and weight using suitable instrumentation and control equipment.",requirements:["Process flow and control objectives","Measurement range, sensor type and installation points","Required control response and operating limits","Alarm, manual mode and failure behavior"],sequence:["Define process variables and acceptable operating states","Confirm sensors, actuators and signal interfaces","Configure control logic and operator setpoints","Review loop behavior and fault response","Verify against the process specification"],controls:[{title:"Instrumentation and feedback",body:"Control performance depends on measurement selection, installation, process response and actuator capability. Instrument ranges and limits must come from the process design."},{title:"PID and process loops",body:"PID control can be considered when the process needs continuous regulation and the instrument and actuator arrangement support it. Tuning and operating limits are application-specific."}],products:["plc","hmi","sensors","vfd-drives","industrial-communication"],services:["plc","hmi","scada","panel"],related:["temperature-control","pressure-control","flow-control","level-control","pid-control","weighing-automation"]},
  {slug:"machine-automation",name:"Machine Automation",group:"Automation Engineering",overview:"Machine automation coordinates a machine's sequence, operator controls, instrumentation and connected drives around its intended operation.",requirements:["Machine function and cycle sequence","Current controller, drawings and I/O","Required modes, interlocks and fault recovery","Interfaces with operators and adjacent equipment"],sequence:["Review machine behavior and existing controls","Map states, signals and operator actions","Define control sequence and fault responses","Implement and verify relevant interfaces","Document machine changes and handover"],controls:automationControls("machine"),products:["plc","hmi","vfd-drives","sensors","control-panels"],services:["plc","hmi","vfd","panel","machine","retrofit"],related:["custom-machine-automation","special-purpose-machine-automation","automation-retrofit"]},
  {slug:"hmi",name:"HMI Operator Interfaces",group:"Technology",overview:"An industrial HMI presents machine status, alarms, setpoints and operator commands through screens designed around the operating process.",requirements:["Operator roles and required screen views","Machine states, alarms and process values","Setpoint limits and command permissions","PLC communication interface"],sequence:["Map operator tasks and machine states","Organize screens, navigation and alarm presentation","Connect required values to the controller","Review access and command behavior","Verify screen behavior with the operating sequence"],controls:[{title:"HMI screens and alarms",body:"Screen content should support the actual operator tasks. Alarm descriptions, priorities, acknowledgements and reset actions depend on the site's procedures."}],products:["hmi","plc","industrial-communication"],services:["hmi","plc"],related:["hmi-programming","plc-programming","scada-programming"]},
  {slug:"hmi-programming",name:"HMI Programming Services",group:"Engineering Services",overview:"HMI programming connects operator screens to controller data and machine behavior, with navigation and alarms suited to the application.",requirements:["Existing HMI model and project access","Screen list, tags and machine states","Alarm and setpoint handling requirements","PLC communication details"],sequence:["Review operator workflow and control project","Define screens, tags, alarms and navigation","Implement the interface for the installed platform","Review permissions and controller interaction","Verify using the machine sequence and handover requirements"],controls:commonControls(),products:["hmi","plc","industrial-communication"],services:["hmi","plc"],related:["hmi","plc-programming","scada-programming"]},
  {slug:"scada-programming",name:"SCADA Programming and Integration",group:"Engineering Services",overview:"SCADA systems can provide supervisory views of distributed equipment, process values and alarms where the architecture and communication interfaces support them.",requirements:["Equipment and site architecture","Required supervisory screens, trends or alarms","Available PLC communication protocols","User access, data retention and network constraints"],sequence:["Review the control network and data sources","Define supervisory views, alarms and required history","Connect supported devices and validate tag mapping","Review user access and communication loss behavior","Verify operation with the site's IT and control requirements"],controls:[{title:"Supervisory monitoring",body:"SCADA scope depends on the selected platform, device interfaces, network design and operational requirements. It should be coordinated with the site's controls and IT teams."}],products:["plc","hmi","industrial-communication"],services:["scada","plc","hmi"],related:["process-automation","plc-programming","hmi-programming"]},
  {slug:"vfd",name:"VFDs and Motor Control",group:"Technology",overview:"Variable frequency drives provide adjustable motor speed control where the motor, load and process requirements support variable-speed operation.",requirements:["Motor nameplate and load characteristics","Required speed range and operating duty","Control and feedback signals","Electrical installation and protection requirements"],sequence:["Review motor, load and process operating needs","Confirm suitable drive and interface","Define speed references, status and fault behavior","Verify operation against machine constraints","Document settings and interfaces"],controls:[{title:"Motor speed control",body:"A VFD can support speed adjustment, but the usable range and control method depend on motor, drive, load, cooling and machine safety requirements."}],products:["vfd-drives","plc","sensors"],services:["vfd","plc","panel"],related:["vfd-programming","pump-automation","conveyor-automation"]},
  {slug:"vfd-programming",name:"VFD Programming Services",group:"Engineering Services",overview:"VFD configuration and PLC integration align drive commands, speed references, status signals and fault handling with a machine sequence.",requirements:["Drive and motor model details","Application load and speed requirements","PLC interface and command method","Existing parameters and fault history"],sequence:["Review drive, motor and application details","Agree command, reference and feedback signals","Configure drive and controller interaction","Check protection and fault response","Record approved parameter changes"],controls:[{title:"Drive integration and limits",body:"Parameter changes should follow the drive and motor documentation and the machine's operating limits. No compatibility is assumed until the installed model is known."}],products:["vfd-drives","plc","industrial-communication"],services:["vfd","plc","retrofit"],related:["vfd","conveyor-automation","pump-automation"]},
  {slug:"servo-automation",name:"Servo Automation",group:"Technology",overview:"Servo systems can provide controlled positioning or coordinated motion when the mechanics, feedback and motion requirements call for them.",requirements:["Axis mechanics, load and travel","Position, speed or torque requirements","Feedback and homing arrangements","Synchronization and stopping behavior"],sequence:["Define axis behavior and operating envelope","Review motor, drive and mechanical compatibility","Map motion commands and feedback","Verify limits, homing and fault responses","Document tuning and commissioning assumptions"],controls:[{title:"Axis control",body:"Servo selection and tuning depend on the motor, drive, mechanics, load and required motion profile. Specific performance cannot be assumed without those details."}],products:["servo-systems","plc","sensors"],services:["vfd","plc","machine"],related:["motion-control","cut-to-length-automation","printing-machine-automation"]},
  {slug:"motion-control",name:"Industrial Motion Control",group:"Technology",overview:"Motion control coordinates speed, position and synchronization for machine axes using compatible drives, feedback and controller capabilities.",requirements:["Axis count and machine mechanics","Motion profile and synchronization needs","Feedback devices and homing method","Safe motion and fault recovery requirements"],sequence:["Describe required axis behavior","Confirm controller and drive capabilities","Define motion states, references and feedback","Review limit and fault handling","Verify coordinated behavior on the machine"],controls:[{title:"Position and synchronization",body:"Positioning and synchronization require compatible controller, drive, feedback and mechanics. The design should be based on the machine's actual motion requirements."}],products:["servo-systems","vfd-drives","plc","sensors"],services:["plc","vfd","machine"],related:["servo-automation","cut-to-length-automation","winding-automation"]},
  {slug:"control-panels",name:"Industrial Control Panels",group:"Engineering Services",overview:"Control panel scope can include arrangement of automation components and electrical interfaces around documented machine and project requirements.",requirements:["Electrical drawings and equipment list","Power, protection and control requirements","Panel environment and installation constraints","Applicable project standards and inspection needs"],sequence:["Review drawings, loads and control architecture","Confirm components and panel interfaces","Develop or update panel design documentation","Build or modify to the agreed scope","Review wiring and support commissioning"],controls:[{title:"Panel design and interfaces",body:"Panel layout, component ratings, wiring and protective devices must be engineered for the actual installation and applicable requirements. A project review is needed before confirming scope."}],products:["control-panels","plc","hmi","vfd-drives","industrial-communication"],services:["panel","plc","machine"],related:["plc-programming","machine-automation","automation-retrofit"]},
  {slug:"custom-machine-automation",name:"Custom Machine Automation",group:"Automation Engineering",overview:"Custom machine automation starts with the required machine function and develops a control approach around its mechanics, sequence, operator workflow and interfaces.",requirements:["Machine concept or existing equipment","Required cycle and production workflow","Operator, sensor and actuator interfaces","Space, utility and safety constraints"],sequence:["Clarify the machine function and scope","Review the mechanical and electrical interfaces","Define states, controls and operator workflow","Implement agreed automation elements","Verify operation and document remaining assumptions"],controls:automationControls("machine"),products:["plc","hmi","vfd-drives","servo-systems","sensors","control-panels"],services:["machine","plc","hmi","panel"],related:["special-purpose-machine-automation","machine-automation","automation-retrofit"]},
  {slug:"automation-retrofit",name:"Automation Retrofit and PLC Replacement",group:"Engineering Services",overview:"Automation retrofit reviews existing machine controls and replaces or modifies selected components while accounting for legacy wiring, interfaces and operating behavior.",requirements:["Installed controller, HMI and drive details","Electrical drawings and I/O list if available","Current cycle, faults and known limitations","Required downtime and restart constraints"],sequence:["Survey existing controls, wiring and machine behavior","Define replacement boundaries and compatibility needs","Plan signal migration and operating sequence verification","Implement agreed changes with controlled backups","Commission and document differences from the original system"],controls:[{title:"Legacy interface review",body:"Retrofit planning depends on the installed hardware, available drawings, software access and machine condition. Compatibility and downtime should be assessed before committing to a design."},...automationControls("machine")],products:["plc","hmi","vfd-drives","control-panels","industrial-communication"],services:["retrofit","plc","hmi","vfd","panel"],related:["machine-automation","plc-programming","control-panels"]},
  {slug:"temperature-control",name:"Industrial Temperature Control",group:"Process Automation",overview:"Temperature control uses suitable measurement and control equipment to regulate a process within its defined operating requirements.",requirements:["Process material and required temperature range","Sensor type, placement and response","Heating or cooling actuator arrangement","Setpoint, alarm and manual mode requirements"],sequence:["Confirm process target and allowable limits","Review sensor and actuator installation","Define control mode, output limits and alarms","Review response across relevant operating conditions","Verify behavior against the process specification"],controls:[{title:"Temperature measurement and PID",body:"PID control may be appropriate when process response and equipment support continuous regulation. Sensor location, thermal lag, actuator limits and tuning requirements shape the design."}],products:["plc","hmi","sensors","industrial-communication"],services:["plc","hmi","panel"],related:["process-automation","pid-control","heat-treatment-furnace-automation","ahu-automation"]},
  {slug:"pressure-control",name:"Industrial Pressure Control",group:"Process Automation",overview:"Pressure control combines an appropriate pressure measurement with a control strategy suited to the fluid system and connected equipment.",requirements:["Fluid, operating range and pressure target","Transmitter range and installation point","Pump, valve or compressor actuator","Protection limits and fault response"],sequence:["Confirm target range and process demand","Review pressure feedback and actuator capabilities","Define start, stop and regulation behavior","Set alarm and protective conditions from project requirements","Verify response under expected operating conditions"],controls:[{title:"Pressure loop and PID",body:"Continuous pressure regulation may use PID when the sensor, actuator and process are suitable. Protection limits and tuning must follow the system design and equipment requirements."}],products:["plc","hmi","vfd-drives","sensors"],services:["plc","hmi","vfd","panel"],related:["process-automation","pid-control","pump-automation","booster-pump-automation"]},
  {slug:"flow-control",name:"Industrial Flow Control",group:"Process Automation",overview:"Flow control monitors and adjusts material movement using suitable flow measurement and control equipment for the process.",requirements:["Fluid or material properties and flow range","Meter type, installation and signal interface","Control element such as pump or valve","Required operating modes and alarm conditions"],sequence:["Define flow targets and measurement range","Confirm instrument and actuator interfaces","Map control behavior and operating limits","Review alarms and loss-of-signal response","Verify measurement and control against project needs"],controls:[{title:"Flow measurement and regulation",body:"Flow loop performance depends on meter selection, installation conditions and actuator authority. Instrument compatibility and ranges require project-specific confirmation."}],products:["plc","hmi","sensors","vfd-drives"],services:["plc","hmi","panel"],related:["process-automation","pid-control","pump-automation"]},
  {slug:"level-control",name:"Tank and Vessel Level Control",group:"Process Automation",overview:"Level control monitors material in a tank or vessel and coordinates filling, transfer or draining according to defined operating limits.",requirements:["Vessel geometry and process medium","Level switch or transmitter type and range","Inlet, outlet and pump or valve interfaces","High/low alarms and overflow or dry-run protections"],sequence:["Check level signal validity and operating mode","Start or stop transfer equipment at defined conditions","Monitor high and low limits","Alarm abnormal or contradictory signals","Require defined checks before returning to service"],controls:[{title:"Level sensing and pump coordination",body:"The suitable sensor depends on tank geometry and process medium. Pump interlocks and limits should reflect the actual process and installed protection."}],products:["plc","hmi","sensors","vfd-drives"],services:["plc","hmi","panel"],related:["process-automation","pump-automation","pid-control"]},
  {slug:"pid-control",name:"PID Control for Industrial Processes",group:"Process Automation",overview:"PID control can regulate a process variable by adjusting a suitable actuator in response to measured error, where the process and equipment support closed-loop control.",requirements:["Measured variable and suitable instrument","Actuator with adequate control authority","Process dynamics and operating range","Setpoint, manual/automatic transfer and failure behavior"],sequence:["Validate measurement scaling and direction","Confirm output limits and actuator response","Define setpoint and mode behavior","Tune against the process response using an approved method","Verify alarms, manual operation and recovery"],controls:[{title:"Loop design and tuning",body:"PID settings are specific to the process, instrument and actuator. Tuning should be based on observed response and safe operating limits; no generic parameter values are suitable for every machine."}],products:["plc","hmi","sensors","vfd-drives"],services:["plc","hmi","panel"],related:["process-automation","temperature-control","pressure-control","flow-control"]},
  {slug:"weighing-automation",name:"Industrial Weighing Automation",group:"Process Automation",overview:"Industrial weighing automation connects weighing equipment to machine or process sequences for measured dosing, check weighing or batch handling.",requirements:["Weighing device, load cell and signal conditioner details","Required capacity, resolution and tolerance","Mechanical mounting and material loading behavior","Zero, tare, calibration and fault handling procedure"],sequence:["Confirm scale status and zero or tare condition","Add or dose material under configured conditions","Monitor measured value and stable-state behavior","Handle tolerance or signal faults as specified","Record or pass the accepted measurement to the next step"],controls:[{title:"Load-cell and weighing integration",body:"Load-cell compatibility and weighing performance depend on the cells, mounting, signal conditioning, mechanical forces and calibration process. Capacity and accuracy must be confirmed from the equipment specification."}],products:["plc","hmi","sensors","industrial-communication"],services:["plc","hmi","panel"],related:["sand-mixing-plant-automation","batching-plant-automation","process-automation"]},
  {slug:"special-purpose-machine-automation",name:"Special Purpose Machine Automation",group:"Automation Engineering",overview:"Special purpose machine automation defines controls for equipment designed around a specific production task, sequence and operator workflow.",requirements:["Machine function and production task","Cycle steps, tooling and material handling","Controller, drives and installed instrumentation","Safety, operator roles and fault recovery"],sequence:["Clarify functional requirements and machine states","Map sensors, actuators and operator interactions","Define the control sequence and abnormal cases","Implement the agreed control and interface scope","Review operation with the machine and project team"],controls:automationControls("machine"),products:["plc","hmi","vfd-drives","servo-systems","sensors","control-panels"],services:["machine","plc","hmi","panel"],related:["custom-machine-automation","machine-automation","automation-retrofit"]},
];
export const capabilityPages = capabilitySeeds.map(makeApp);
export const capabilityBySlug = new Map(capabilityPages.map((page) => [page.slug, page]));
export const capabilitySlugs = capabilityPages.map(({ slug }) => slug);
