import Link from "next/link";
import Image from "next/image";
import { prisma } from "@/lib/prisma";
import type { SeoPage } from "@/lib/seo-content";
import { applicationBySlug, capabilityBySlug } from "@/lib/seo-content";
import StoreHeader from "@/components/layout/StoreHeader";
import SiteFooter from "@/components/site/SiteFooter";
import BreadcrumbJsonLd from "@/components/seo/BreadcrumbJsonLd";

const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://smartplcsolutions.com").replace(/\/$/, "");
const categoryLabels: Record<string, string> = { plc:"PLC", hmi:"HMI", "vfd-drives":"VFD & Drives", "servo-systems":"Servo Systems", sensors:"Sensors", "industrial-communication":"Industrial Communication", "control-panels":"Control Panels" };

export default async function AutomationContentPage({ page, family }: { page: SeoPage; family: "application" | "capability" }) {
  const categories = await prisma.category.findMany({ where: { active: true, slug: { in: page.productCategories } }, select: { id: true, name: true, slug: true } });
  const products = categories.length ? await prisma.product.findMany({
    where: { status: "ACTIVE", categoryId: { in: categories.map(({ id }) => id) } },
    select: { slug: true, name: true, shortDescription: true, images: { where: { isPrimary: true }, take: 1, select: { url: true, altText: true } }, category: { select: { name: true } } },
    orderBy: [{ featured: "desc" }, { createdAt: "desc" }], take: 8,
  }) : [];
  const crumbs = [{ name: "Home", url: siteUrl }, { name: "Industrial Automation", url: `${siteUrl}/industrial-automation` }, ...(family === "application" ? [{ name: "Applications", url: `${siteUrl}/applications` }] : []), { name: page.h1, url: `${siteUrl}${family === "application" ? "/applications" : ""}/${page.slug}` }];
  const sectionClass = "mx-auto max-w-6xl px-5 py-12 sm:px-8";
  return <main className="min-h-screen bg-white text-slate-900"><StoreHeader/><BreadcrumbJsonLd items={crumbs}/>
    <nav aria-label="Breadcrumb" className="mx-auto max-w-6xl px-5 pt-7 text-sm text-slate-500 sm:px-8"><ol className="flex flex-wrap gap-2">{crumbs.map((crumb, i)=><li key={crumb.url} className="flex gap-2">{i > 0 && <span aria-hidden="true">/</span>}{i === crumbs.length - 1 ? <span aria-current="page">{crumb.name}</span> : <Link className="hover:text-sky-700" href={crumb.url.replace(siteUrl, "") || "/"}>{crumb.name}</Link>}</li>)}</ol></nav>
    <header className="bg-[#101c2b] px-5 py-14 text-white sm:px-8 sm:py-16"><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-sky-300">{page.group}</p><h1 className="mt-3 max-w-4xl text-4xl font-bold sm:text-5xl">{page.h1}</h1><p className="mt-6 max-w-3xl text-base leading-7 text-slate-300">{page.intro}</p><div className="mt-7 flex flex-wrap gap-3"><Link href={`/request-quote?type=service&service=${encodeURIComponent(page.serviceLinks[0]?.service ?? "Machine Automation")}&subject=${encodeURIComponent(page.h1)}`} className="bg-sky-500 px-5 py-3 text-sm font-semibold text-white hover:bg-sky-400">Request a Quote</Link><a href="https://wa.me/917456812005" target="_blank" rel="noopener noreferrer" className="border border-white/40 px-5 py-3 text-sm font-semibold text-white hover:bg-white/10">Discuss on WhatsApp</a></div></div></header>
    <section className={sectionClass}><h2 className="text-2xl font-bold">Application overview</h2><p className="mt-4 max-w-4xl leading-7 text-slate-600">{page.overview}</p><div className="mt-8 grid gap-8 lg:grid-cols-2"><div><h3 className="text-lg font-bold">Typical requirements to define</h3><ul className="mt-4 list-disc space-y-2 pl-5 leading-6 text-slate-600">{page.requirements.map((x)=><li key={x}>{x}</li>)}</ul></div><div><h3 className="text-lg font-bold">Example process sequence</h3><ol className="mt-4 list-decimal space-y-2 pl-5 leading-6 text-slate-600">{page.sequence.map((x)=><li key={x}>{x}</li>)}</ol></div></div></section>
    <section className="bg-slate-50"><div className={`${sectionClass} grid gap-5 md:grid-cols-2`}>{page.controls.map((control)=><article key={control.title} className="border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">{control.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{control.body}</p>{control.bullets?.length ? <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-600">{control.bullets.map((item)=><li key={item}>{item}</li>)}</ul> : null}</article>)}</div></section>
    <section className={sectionClass}><h2 className="text-2xl font-bold">Related automation technologies</h2><p className="mt-2 text-slate-600">Explore the control systems that may be relevant to this scope.</p><div className="mt-5 flex flex-wrap gap-3">{page.technologies.map((item)=><Link key={item.href} href={item.href} className="border border-slate-300 px-4 py-2 text-sm font-medium text-sky-800 hover:border-sky-500">{item.label}</Link>)}{page.productCategories.map((slug)=>categories.some((c)=>c.slug===slug) ? <Link key={slug} href={`/products/category/${slug}`} className="border border-slate-300 px-4 py-2 text-sm font-medium text-sky-800 hover:border-sky-500">{categoryLabels[slug] ?? slug} products</Link> : null)}</div></section>
    {products.length > 0 && <section className="bg-slate-50"><div className={sectionClass}><h2 className="text-2xl font-bold">Products from the catalog</h2><p className="mt-2 text-slate-600">These active catalog products are related by their existing category. Confirm model compatibility and availability for your application.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{products.map((product)=><Link key={product.slug} href={`/products/${product.slug}`} className="border border-slate-200 bg-white p-4 hover:border-sky-500">{product.images[0] && <Image src={product.images[0].url} alt={product.images[0].altText || product.name} width={480} height={320} className="mb-3 aspect-[3/2] w-full object-contain"/>}<p className="text-xs font-semibold uppercase tracking-wide text-sky-700">{product.category.name}</p><h3 className="mt-1 font-semibold">{product.name}</h3>{product.shortDescription && <p className="mt-2 line-clamp-3 text-sm text-slate-600">{product.shortDescription}</p>}</Link>)}</div></div></section>}
    <section className={sectionClass}><h2 className="text-2xl font-bold">Related engineering services</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{page.serviceLinks.map((service)=><Link key={service.service} href={`/request-quote?type=service&service=${encodeURIComponent(service.service)}&subject=${encodeURIComponent(page.h1)}`} className="border border-slate-200 p-5 hover:border-sky-500"><h3 className="font-semibold">{service.label}</h3><p className="mt-2 text-sm leading-6 text-slate-600">Discuss the equipment, existing controls and project requirements with our engineering team.</p><span className="mt-4 inline-block text-sm font-semibold text-sky-700">Request service quote →</span></Link>)}</div><Link href="/services" className="mt-5 inline-block text-sm font-semibold text-sky-700">View automation services →</Link></section>
    {page.related.length > 0 && <section className="bg-slate-50"><div className={sectionClass}><h2 className="text-2xl font-bold">Related applications and topics</h2><div className="mt-5 flex flex-wrap gap-3">{page.related.map((slug)=>{const capability=capabilityBySlug.get(slug);const application=applicationBySlug.get(slug);const href=slug==="applications"?"/applications":capability?`/${slug}`:`/applications/${slug}`;const label=capability?.h1||application?.h1||slug.split("-").map((part)=>part[0]?.toUpperCase()+part.slice(1)).join(" ");return <Link key={slug} href={href} className="border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-sky-800 hover:border-sky-500">{label}</Link>;})}</div></div></section>}
    <section className={sectionClass}><h2 className="text-2xl font-bold">Frequently asked questions</h2><div className="mt-5 divide-y divide-slate-200">{page.faqs.map((faq)=><article key={faq.question} className="py-5"><h3 className="font-semibold">{faq.question}</h3><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-600">{faq.answer}</p></article>)}</div></section>
    <section className="bg-[#101c2b] px-5 py-12 text-white sm:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-bold">Discuss your automation requirements</h2><p className="mt-2 text-slate-300">Share the equipment details, current controls and process sequence for a scope review.</p></div><Link href={`/request-quote?type=service&subject=${encodeURIComponent(page.h1)}`} className="inline-flex w-fit bg-sky-500 px-5 py-3 text-sm font-semibold hover:bg-sky-400">Request a Quote</Link></div></section><SiteFooter/></main>;
}
