export const dynamic = "force-dynamic";
import type { Metadata } from "next";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import StoreHeader from "@/components/layout/StoreHeader";
import SiteFooter from "@/components/site/SiteFooter";
import ProductCardPrice from "@/components/home/ProductCardPrice";

export const metadata: Metadata = { title: "Industrial Automation Products & Engineering Services", description: "Industrial automation products and engineering services for PLC, HMI, SCADA, drives, sensors, communication and control panels.", alternates: { canonical: "/" } };
const categories = [
  ["PLC","plc","Controllers, CPUs and expansion I/O"],["HMI","hmi","Operator panels and interfaces"],["VFD & Drives","vfd-drives","Variable frequency drives and motor control"],["Servo Systems","servo-systems","Servo drives, motors and accessories"],["Sensors","sensors","Industrial sensing and measurement"],["Control Panels","control-panels","Panel and electrical components"],["Industrial Communication","industrial-communication","Industrial networks and interfaces"],["New Machines","automation-components","New machines and production equipment for industrial automation applications"],
];
const services = [
  ["PLC Programming","Logic development, modification and troubleshooting for industrial controls."],["HMI & SCADA","Operator interface design, visualization and integration support."],["VFD & Servo","Drive configuration, motion setup and application support."],["Machine Automation","Control upgrades and automation integration for machinery."],["Control Panel Engineering","Panel design, documentation and manufacturing enquiries."],["Commissioning & Support","On-site or remote commissioning and troubleshooting enquiries."],
];
export default async function Home() {
 const featured = await prisma.product.findMany({ where:{status:"ACTIVE",featured:true},include:{category:true,images:{orderBy:[{isPrimary:"desc"},{sortOrder:"asc"}],take:1}},orderBy:{createdAt:"desc"},take:8 });
 return <main className="min-h-screen bg-white text-slate-900"><StoreHeader />
  <section className="relative overflow-hidden bg-[#101c2b] text-white"><div className="absolute inset-0 opacity-30" style={{backgroundImage:"linear-gradient(rgba(65,155,212,.22) 1px,transparent 1px),linear-gradient(90deg,rgba(65,155,212,.22) 1px,transparent 1px)",backgroundSize:"44px 44px"}}/><div className="relative mx-auto grid min-h-[520px] max-w-7xl items-center gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:py-24"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-sky-300">Industrial controls · Engineering · Supply</p><h1 className="mt-5 max-w-3xl text-4xl font-bold leading-tight sm:text-5xl lg:text-6xl">Industrial Automation Solutions for Modern Manufacturing</h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">PLC, HMI, SCADA, VFD, servo, control panel and machine automation products and services.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="bg-sky-500 px-6 py-3 text-sm font-semibold text-white hover:bg-sky-400">Explore Products</Link><Link href="/request-quote" className="border border-white/40 px-6 py-3 text-sm font-semibold text-white hover:bg-white/10">Request a Quote</Link></div><Link href="/contact" className="mt-6 inline-block text-sm text-sky-200 underline underline-offset-4">Talk to an automation engineer</Link></div><img src="/industrial-control-panel.svg" alt="Illustration of an industrial control panel with PLC, operator display and electrical controls" className="mx-auto w-full max-w-lg drop-shadow-2xl"/></div></section>
  <section className="border-b border-slate-200 bg-slate-50"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-y divide-slate-200 sm:grid-cols-4 sm:divide-y-0">{["PLC, HMI & SCADA","Drives & Motion","Panel Engineering","Commissioning Support"].map(x=><div key={x} className="px-4 py-5 text-center text-xs font-semibold uppercase tracking-wider text-slate-600 sm:py-6">{x}</div>)}</div></section>
  <section className="bg-slate-50 py-16 lg:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-sky-700">Selected products</p><h2 className="mt-2 text-3xl font-bold sm:text-4xl">Featured Products</h2></div><Link href="/products" className="text-sm font-semibold text-sky-700">View catalog →</Link></div>{featured.length?<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{featured.map(p=><Link key={p.id} href={`/products/${p.slug}`} className="overflow-hidden border border-slate-200 bg-white hover:shadow-lg"><div className="aspect-[4/3] bg-slate-100">{p.images[0]?.url?<img src={p.images[0].url} alt={p.images[0].altText||p.name} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-sm font-semibold uppercase tracking-widest text-slate-400">{p.category.name}</div>}</div><div className="p-4"><p className="text-xs font-semibold uppercase tracking-wider text-sky-700">{p.category.name}</p><h3 className="mt-2 font-semibold">{p.name}</h3><p className="mt-2 text-sm text-slate-600">{p.shortDescription}</p><ProductCardPrice priceUSD={Number(p.basePrice)} compareAtPriceUSD={p.compareAtPrice === null ? null : Number(p.compareAtPrice)}/></div></Link>)}</div>:<div className="mt-8 border border-dashed border-slate-300 bg-white p-8 text-center"><p className="font-semibold">Product listings are being prepared.</p><p className="mt-2 text-sm text-slate-600">Contact us with your part number or application for availability and pricing.</p><Link href="/request-quote" className="mt-4 inline-flex bg-sky-600 px-5 py-3 text-sm font-semibold text-white">Request product pricing</Link></div>}</div></section>
  <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-20"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-sky-700">Product range</p><h2 className="mt-2 text-3xl font-bold sm:text-4xl">Automation Products</h2></div><Link href="/products" className="text-sm font-semibold text-sky-700">Browse all products →</Link></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:gap-4">{categories.map(([name,slug,desc])=><Link key={slug} href={`/products?category=${slug}`} className="group border border-slate-200 p-5 transition hover:border-sky-400 hover:shadow-md sm:p-6"><span className="text-xs font-bold tracking-[.18em] text-sky-700">CONTROL SYSTEMS</span><h3 className="mt-4 text-lg font-bold group-hover:text-sky-700">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{desc}</p><span className="mt-5 inline-block text-sm font-semibold text-sky-700">View range →</span></Link>)}</div></section>
  <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-20"><p className="text-xs font-semibold uppercase tracking-[.22em] text-sky-700">Engineering services</p><h2 className="mt-2 text-3xl font-bold sm:text-4xl">Support Across Your Automation Project</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Share your equipment, process requirements and project scope. We’ll review your enquiry and discuss suitable next steps.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(([name,desc])=><Link key={name} href={`/request-quote?service=${encodeURIComponent(name)}`} className="border border-slate-200 p-6 hover:border-sky-400 hover:shadow-md"><h3 className="font-bold">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{desc}</p><span className="mt-4 inline-block text-sm font-semibold text-sky-700">Enquire about this service →</span></Link>)}</div></section>
  <section className="bg-[#101c2b] px-5 py-14 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-sky-300">Engineering-led support</p><h2 className="mt-2 text-2xl font-bold sm:text-3xl">Have a controls or machine automation requirement?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Send your application details, existing equipment information and target outcomes to start a technical conversation.</p></div><Link href="/request-quote" className="shrink-0 bg-sky-500 px-6 py-3 text-sm font-semibold">Request a Quote</Link></div></section><SiteFooter/></main>;
}

