import type { Metadata } from "next";
import Link from "next/link";
import StoreHeader from "@/components/layout/StoreHeader";
import SiteFooter from "@/components/site/SiteFooter";
import BreadcrumbJsonLd from "@/components/seo/BreadcrumbJsonLd";
import { applicationHubGroups, applicationBySlug, capabilityBySlug } from "@/lib/seo-content";

const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || "https://smartplcsolutions.com").replace(/\/$/, "");
export const metadata: Metadata = { title: "Industrial Automation Applications", description: "Explore SmartPLC Solutions application topics across machine automation, process control, printing and converting, and industrial utilities.", alternates: { canonical: "/applications" }, openGraph: { type: "website", title: "Industrial Automation Applications", description: "Explore industrial automation application topics and engineering considerations.", url: "/applications", images: [{ url: "/og-smart-plc.png", width: 1200, height: 630, alt: "Industrial Automation Applications | SmartPLC Solutions" }] }, twitter: { card: "summary_large_image", title: "Industrial Automation Applications", description: "Explore industrial automation application topics and engineering considerations.", images: ["/og-smart-plc.png"] } };

export default function ApplicationsIndex() {
  const crumbs = [{ name: "Home", url: siteUrl }, { name: "Industrial Automation", url: `${siteUrl}/industrial-automation` }, { name: "Applications", url: `${siteUrl}/applications` }];
  return <main className="min-h-screen bg-white text-slate-900"><StoreHeader/><BreadcrumbJsonLd items={crumbs}/><nav aria-label="Breadcrumb" className="mx-auto max-w-6xl px-5 pt-7 text-sm text-slate-500 sm:px-8"><Link href="/" className="hover:text-sky-700">Home</Link><span className="mx-2">/</span><span aria-current="page">Applications</span></nav>
    <header className="bg-[#101c2b] px-5 py-14 text-white sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-sky-300">Industrial Automation</p><h1 className="mt-3 max-w-4xl text-4xl font-bold sm:text-5xl">Automation applications and machine control</h1><p className="mt-6 max-w-3xl leading-7 text-slate-300">SmartPLC Solutions works across automation products and engineering enquiries for machines, production processes and plant utilities. These application guides outline the information, sequence and control topics to consider when defining a project. The appropriate design depends on the installed equipment, process, controls and operating requirements.</p><Link href="/request-quote?type=service" className="mt-7 inline-flex bg-sky-500 px-5 py-3 text-sm font-semibold hover:bg-sky-400">Discuss an application</Link></div></header>
    <section className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><h2 className="text-2xl font-bold">Explore automation by application</h2><p className="mt-3 max-w-3xl leading-7 text-slate-600">Browse application guides by machine and process family. Each guide describes common control considerations; actual PLC, drive, instrumentation and safety scope depends on the installed equipment and project requirements.</p><div className="mt-7 grid gap-5 md:grid-cols-2">{applicationHubGroups.map((group)=>{const items=group.slugs.map((slug)=>applicationBySlug.get(slug)).filter((page)=>page !== undefined);if(!items.length)return null;return <section key={group.title} className="border border-slate-200 p-6"><h3 className="text-xl font-bold">{group.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{group.description}</p><ul className="mt-3 divide-y divide-slate-100">{items.map((page)=><li key={page.slug}><Link href={`/applications/${page.slug}`} className="flex items-center justify-between gap-3 py-3 text-sm font-medium hover:text-sky-700"><span>{page.h1}</span><span aria-hidden="true">→</span></Link></li>)}</ul></section>;})}
      <section className="border border-slate-200 p-6"><h2 className="text-xl font-bold">Process Automation &amp; Control</h2><p className="mt-2 text-sm leading-6 text-slate-600">Explore measurement and control topics that may connect to industrial processes and machine applications.</p><ul className="mt-4 divide-y divide-slate-100">{["process-automation","temperature-control","pressure-control","flow-control","level-control","pid-control","weighing-automation"].map((slug)=>{const page=capabilityBySlug.get(slug);if(!page)return null;return <li key={slug}><Link href={`/${slug}`} className="flex items-center justify-between gap-3 py-3 text-sm font-medium hover:text-sky-700"><span>{page.h1}</span><span aria-hidden="true">→</span></Link></li>;})}</ul></section>
    </div></section>
    <section className="bg-slate-50"><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><h2 className="text-2xl font-bold">Technology and engineering</h2><p className="mt-3 max-w-3xl leading-7 text-slate-600">Application requirements connect to PLC, HMI, drive, instrumentation and panel decisions. Explore related engineering and process topics or browse actual catalog categories.</p><div className="mt-5 flex flex-wrap gap-3">{[["Industrial automation","/industrial-automation"],["PLC programming","/plc-programming"],["Process automation","/process-automation"],["Machine automation","/machine-automation"],["Engineering services","/services"],["Products","/products"]].map(([name,href])=><Link key={href} href={href} className="border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-sky-800 hover:border-sky-500">{name}</Link>)}</div></div></section><SiteFooter/></main>;
}
