-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "gauge12Extra" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "gauge14Extra" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "gauge16Extra" DECIMAL(12,2) NOT NULL DEFAULT 0;
